# Generated by Django 4.0.3 on 2022-09-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_house_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='avatar',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
