# Generated by Django 4.0.3 on 2022-08-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_house_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='type',
            new_name='house_type',
        ),
    ]
