# Generated by Django 4.0.3 on 2022-09-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_image_house_image_one_house_image_three_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseImage',
        ),
    ]
